CHECK_QM_STATUS_TYPE="none"
CHECK_QM_STATUS_REF=""
CHECK_CHANNELS_TYPE="none"
CHECK_CHANNELS_REF=""
CHECK_LISTENERS_TYPE="none"
CHECK_LISTENERS_REF=""
CHECK_QUEUES_TYPE="none"
CHECK_QUEUES_REF=""
CHECK_CLUSTER_STATUS_TYPE="command"
CHECK_CLUSTER_STATUS_REF="demo-cluster-status"
CHECK_CLUSTER_READINESS_TYPE="command"
CHECK_CLUSTER_READINESS_REF="demo-readiness-check"
