TROUBLESHOOT_LOGS_TYPE="none"
TROUBLESHOOT_LOGS_REF=""
TROUBLESHOOT_FDC_TYPE="none"
TROUBLESHOOT_FDC_REF=""
TROUBLESHOOT_ERROR_SCAN_TYPE="none"
TROUBLESHOOT_ERROR_SCAN_REF=""
TROUBLESHOOT_MQ_DIAGNOSTICS_TYPE="none"
TROUBLESHOOT_MQ_DIAGNOSTICS_REF=""
